<h1>RabbitMq, total sent <?php echo $totalMessages; ?></h1>

<?php if($displayCount !== 0 && $totalMessages > $displayCount): ?>
<p>Displayed only first <?php echo $displayCount ?> messages</p>
<?php endif; ?>

<div class="tracy-inner">
	<table class="tracy-bs-main">
		<?php foreach ($sentMessages as $producerName => $producerMessages): ?>
			<tr><th>Producer: <?php echo $producerName ?></th></tr>
		<?php foreach ($producerMessages as $producerMessage): ?>
			<tr>
				<td><pre><?php echo $producerMessage ?></pre></td>
			</tr>
		<?php endforeach ?>
		<?php endforeach ?>
	</table>
</div>
